In [1]:
'''
Practical No.2: Write a NumPy program to implement following operation
Name:panera ghanshyam
Enroll no:216270307072
'''
import numpy as np;# linear algebra
import pandas as pd; # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
'''
to convert a list of numeric values into a one-dimensional NumPy array
'''
List=[10,20,30,40,50];

a=np.array(List);
print(a);

[10 20 30 40 50]


In [3]:
'''
to create a 3x3 matrix with values ranging from 2 to 10
'''

a=[2,3,4];
b=[5,6,7];
c=[8,9,10];

a=np.array([a,b,c]);
print(a);

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
'''
to append values at the end of an array
'''
List=[10,20,30,40,50];

a=np.array(List);
print("Before append:",a);

a=np.append(a,[60]);

print("After append",a);

Before append: [10 20 30 40 50]
After append [10 20 30 40 50 60]
